version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: tienda
      MYSQL_USER: Antris
      MYSQL_PASSWORD: 12345
    networks:
      - net_tienda

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: Antris
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: tienda
      WORDPRESS_DEBUG: 1
    networks:
      - net_tienda
    ports:
    - "8000:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "8080:80"
    networks:
      - net_tienda

volumes:
  db_data:
  wp_data:

networks:
  net_tienda: