version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: Antris
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: BBDD
    volumes:
      - ./html:/var/www/html
    networks:
      - wp_network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: BBDD
      MYSQL_USER: Antris
      MYSQL_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "8081:80"
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge

volumes:
  db_data: