version: '3.8'

services:
  # Servicio de MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: BBDD
      MYSQL_USER: Antris
      MYSQL_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - app-network

  # Servicio de WordPress
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: Antris
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: BBDD
    ports:
      - '8000:80'
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  # Servicio de PHP + Apache
  php:
    image: php:7.4-apache
    container_name: php-apache
    ports:
      - "8082:80"
    volumes:
      - ./php:/var/www/html
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
